apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockerandkubernates-deployment
spec:
  selector:
    matchLabels:
      app: dockerandkubernates-deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: dockerandkubernates-deployment
    spec:
      containers:
      - name: dockerandkubernates-deployment
        image: docker.io/tushar138/spring-boot-docker-k8s:v1
        ports:
        - containerPort: 8991