apiVersion: v1
kind: Service
metadata:
  name: dockerandkubernates-service
spec:
  type: NodePort
  selector:
    app: dockerandkubernates-deployment
 
  ports:
  - port: 8991
    targetPort: 8991
    nodePort: 32005 